apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: access-pod-group
rules:
- apiGroups:
    - scheduling.volcano.sh
  resources:
    - podgroups
  verbs:
    - get
    - list
    - watch
    - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: access-pod-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: access-pod-group
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:serviceaccount:knative-serving:controller
